from typing import TypedDict, List

class AgentState(TypedDict):
    """
    Represents the state of our multi-agent codebase assistant.
    """
    task: str
    tenant_id: str
    repo_name: str
    
    # Generated by Planner
    plan: str
    search_queries: List[str]
    
    # Generated by Search Node
    context: str
    
    # Generated by Coder
    draft_code: str
    
    # Generated by Reviewer
    review_feedback: str
    review_action: str
    
    # Loop tracking
    revision_number: int
    max_revisions: int
